version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-go-app
    container_name: go-app
    ports:
      - "8080:8080"
    pid: "host"
    restart: unless-stopped
    environment:
      GO_ENV: production
      APP_ENV: prod
      APP_HOST: ${APP_HOST}
      APP_PORT: 8080
      APP_URL: ${APP_URL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXP_MINUTES: ${JWT_ACCESS_EXP_MINUTES}
      JWT_REFRESH_EXP_DAYS: ${JWT_REFRESH_EXP_DAYS}
      JWT_RESET_PASSWORD_EXP_MINUTES: ${JWT_RESET_PASSWORD_EXP_MINUTES}
      JWT_VERIFY_EMAIL_EXP_MINUTES: ${JWT_VERIFY_EMAIL_EXP_MINUTES}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      REDIRECT_URL: ${REDIRECT_URL}
    