// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"encoding/json"

	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type ApiKey struct {
	ent.Schema
}

func (ApiKey) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("user_id").Optional(), field.String("key_name"), field.String("api_key_hash").Unique(), field.String("api_key_prefix"), field.JSON("permissions", json.RawMessage{}).Optional(), field.Int32("rate_limit_per_minute").Optional(), field.Bool("is_active").Optional(), field.Time("last_used_at").Optional(), field.Time("expires_at").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional(), field.Time("deleted_at").Optional()}

}
func (ApiKey) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("api_keys").Unique().Field("user_id")}
}
func (ApiKey) Annotations() []schema.Annotation {
	return nil
}
