// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type PrivacySetting struct {
	ent.Schema
}

func (PrivacySetting) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("user_id").Optional().Unique(), field.Enum("profile_visibility").Optional().Values("public", "friends_only", "private"), field.Bool("show_email").Optional(), field.Bool("show_phone").Optional(), field.Bool("show_birth_date").Optional(), field.Bool("allow_search_engines").Optional(), field.Bool("data_sharing_consent").Optional(), field.Bool("analytics_consent").Optional(), field.Bool("marketing_consent").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}
}
func (PrivacySetting) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("privacy_setting").Unique().Field("user_id")}
}
func (PrivacySetting) Annotations() []schema.Annotation {
	return nil
}
