// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"encoding/json"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type User2fa struct {
	ent.Schema
}

func (User2fa) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("user_id").Optional().Unique(), field.Bool("is_enabled").Optional(), field.String("secret_key").Optional(), field.JSON("backup_codes", json.RawMessage{}).Optional(), field.Enum("method").Optional().Values("totp", "sms", "email"), field.String("phone_number").Optional(), field.String("email_address").Optional(), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}

}
func (User2fa) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("user_2fa").Unique().Field("user_id")}
}
func (User2fa) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "user_2fa"}}
}
