// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type UserSession struct {
	ent.Schema
}

func (UserSession) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("user_id").Optional(), field.String("session_token").Unique(), field.String("device_info").Optional(), field.String("ip_address").Optional(), field.String("user_agent").Optional(), field.Bool("is_active").Optional(), field.Time("expires_at"), field.Time("created_at").Optional(), field.Time("updated_at").Optional()}
}
func (UserSession) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("user_sessions").Unique().Field("user_id")}
}
func (UserSession) Annotations() []schema.Annotation {
	return nil
}
